#!/usr/bin/env node
// render.mjs — Render all MDX docs to static HTML for the Dash docset.
//
// Reads docs/*.md, renders via @mintlify/mdx + @mintlify/components,
// writes HTML to build/_html/. Also copies CSS assets.
//
// Expects REPO_ROOT env var (set by libexec/dash).

import {
  readFileSync,
  writeFileSync,
  copyFileSync,
  readdirSync,
  mkdirSync,
  existsSync,
} from "node:fs";
import { basename, join } from "node:path";
import {
  rewriteLinks,
  injectSectionLabel as _injectSectionLabel,
  convertPageDescription,
  slugify,
  extractTitle,
  injectDashAnchors,
  preprocessMdx,
  truncateChangelog,
  parseNavTabs,
  semverSort,
} from "./dash-transforms.mjs";

const REPO_ROOT = process.env.REPO_ROOT;
if (!REPO_ROOT) {
  console.error("error: REPO_ROOT not set (run via 'navel dash')");
  process.exit(1);
}

const docsDir = join(REPO_ROOT, "docs");
const buildDir = join(REPO_ROOT, "build", "_html");
const dashDir = join(REPO_ROOT, "dash");
const assetsDir = join(REPO_ROOT, "assets");
const dashAssetsDir = join(dashDir, "assets");

// Resolve dash/node_modules deps by direct dist paths — these packages
// only export ESM via "import" (no CJS "require"), so createRequire can't
// resolve them. Direct file imports bypass the exports map entirely.
const nm = join(dashDir, "node_modules");

const { serialize } = await import(join(nm, "@mintlify/mdx/dist/server/index.js"));
const { MDXClient } = await import(join(nm, "@mintlify/mdx/dist/client/default.js"));
const { renderToStaticMarkup } = await import(join(nm, "react-dom/server.js"));
const { createElement } = await import(join(nm, "react/index.js"));
const components = await import(join(nm, "@mintlify/components/dist/index.js"));

// ── Navigation map (generated by fetch-nav.mjs) ────────────────────────
// Maps each slug to its group label, shown above the h1 on the real site.
// Order matches the site navigation structure — controls Dash sidebar ordering.

const navPath = join(REPO_ROOT, "reports", "nav.json");
if (!existsSync(navPath)) {
  console.error("error: reports/nav.json not found — run 'navel nav sync' first");
  process.exit(1);
}
const { navMap: NAV_GROUP_MAP, navOrder: NAV_ORDER } = JSON.parse(readFileSync(navPath, "utf-8"));

// ── Mintlify component map ─────────────────────────────────────────────

const componentMap = {
  ...components,
  Tab: components.Tabs.Item,
  Step: components.Steps.Item,
  AccordionGroup: components.Accordion.Group,
  CardGroup: ({ children }) =>
    createElement("div", { className: "grid grid-cols-2 gap-4" }, children),
  MCPServersTable: () =>
    createElement(
      "p",
      { className: "text-sm italic text-stone-500" },
      "(See MCP documentation for server details)",
    ),
};

// ── Tab switching script (inline, for static-rendered Mintlify Tabs) ───

const TAB_SCRIPT = `<script>
(function() {
  var ACTIVE_CLASSES = 'border-current text-primary dark:text-primary-light';
  var INACTIVE_CLASSES = 'border-transparent text-stone-900 hover:border-stone-300 dark:text-stone-200 dark:hover:border-stone-700';
  var ACTIVE_SET = ACTIVE_CLASSES.split(' ');
  var INACTIVE_SET = INACTIVE_CLASSES.split(' ');

  document.querySelectorAll('[role="tablist"]').forEach(function(tablist) {
    var tabs = Array.from(tablist.querySelectorAll('[role="tab"]'));
    var panelsContainer = tablist.nextElementSibling;
    if (!panelsContainer) return;
    var panels = Array.from(panelsContainer.children).filter(function(el) { return el.getAttribute('role') === 'tabpanel'; });

    tabs.forEach(function(tab, i) {
      tab.addEventListener('click', function() {
        tabs.forEach(function(t) {
          t.setAttribute('aria-selected', 'false');
          t.setAttribute('tabindex', '-1');
          var btn = t.querySelector('[data-component-part="tab-button"]');
          if (btn) {
            btn.setAttribute('data-active', 'false');
            ACTIVE_SET.forEach(function(c) { btn.classList.remove(c); });
            INACTIVE_SET.forEach(function(c) { btn.classList.add(c); });
          }
        });
        panels.forEach(function(p) {
          p.classList.add('hidden');
          p.setAttribute('aria-hidden', 'true');
          p.setAttribute('tabindex', '-1');
        });
        tab.setAttribute('aria-selected', 'true');
        tab.setAttribute('tabindex', '0');
        var btn = tab.querySelector('[data-component-part="tab-button"]');
        if (btn) {
          btn.setAttribute('data-active', 'true');
          INACTIVE_SET.forEach(function(c) { btn.classList.remove(c); });
          ACTIVE_SET.forEach(function(c) { btn.classList.add(c); });
        }
        if (panels[i]) {
          panels[i].classList.remove('hidden');
          panels[i].setAttribute('aria-hidden', 'false');
          panels[i].setAttribute('tabindex', '0');
        }
      });
    });
  });
})();
</script>`;

// ── Inject section label (wraps imported function with NAV_GROUP_MAP) ──

function injectSectionLabel(html, slug) {
  return _injectSectionLabel(html, slug, NAV_GROUP_MAP);
}

// ── Floating buttons script (copy + Ask AI on code blocks) ─────────────

const COPY_SVG =
  '<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M14.25 5.25H7.25C6.14543 5.25 5.25 6.14543 5.25 7.25V14.25C5.25 15.3546 6.14543 16.25 7.25 16.25H14.25C15.3546 16.25 16.25 15.3546 16.25 14.25V7.25C16.25 6.14543 15.3546 5.25 14.25 5.25Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><path d="M2.80103 11.998L1.77203 5.07397C1.61003 3.98097 2.36403 2.96397 3.45603 2.80197L10.38 1.77297C11.313 1.63397 12.19 2.16297 12.528 3.00097" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></svg>';
const CHECK_SVG =
  '<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M3.75 9L7.5 12.75L14.25 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></svg>';
const ASK_AI_SVG =
  '<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M3.51169 1.50098L3.92087 2.72754L3.99997 2.96387L5.49997 3.46387L4.23825 3.88477L4.00095 3.96387L3.92184 4.20117L3.50095 5.46191L3.49997 5.46387H3.49899L2.99899 3.96387L1.49899 3.46387L2.99899 2.96387L3.07809 2.72754L3.4863 1.50098C3.49031 1.50045 3.49522 1.5 3.49997 1.5C3.50416 1.50002 3.50807 1.50054 3.51169 1.50098Z" stroke="currentColor"></path><path d="M9.5 2.75L11.412 7.587L16.25 9.5L11.412 11.413L9.5 16.25L7.587 11.413L2.75 9.5L7.587 7.587L9.5 2.75Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></svg>';

const COPY_SCRIPT = `<script>
(function() {
  var COPY_SVG = '${COPY_SVG.replace(/'/g, "\\'")}';
  var CHECK_SVG = '${CHECK_SVG.replace(/'/g, "\\'")}';
  var ASK_AI_SVG = '${ASK_AI_SVG.replace(/'/g, "\\'")}';

  document.querySelectorAll('pre.shiki').forEach(function(pre) {
    pre.style.position = 'relative';

    var wrapper = document.createElement('div');
    wrapper.className = 'code-buttons';

    // Copy button
    var copyBtn = document.createElement('button');
    copyBtn.className = 'code-btn copy-btn';
    copyBtn.setAttribute('aria-label', 'Copy code');
    copyBtn.innerHTML = COPY_SVG;
    copyBtn.addEventListener('click', function() {
      var code = pre.querySelector('code');
      var text = code ? code.textContent : pre.textContent;
      navigator.clipboard.writeText(text).then(function() {
        copyBtn.innerHTML = CHECK_SVG;
        setTimeout(function() { copyBtn.innerHTML = COPY_SVG; }, 1500);
      });
    });

    // Ask AI button (opens Claude with the code)
    var aiBtn = document.createElement('button');
    aiBtn.className = 'code-btn ask-ai-btn';
    aiBtn.setAttribute('aria-label', 'Ask AI');
    aiBtn.innerHTML = ASK_AI_SVG;
    aiBtn.addEventListener('click', function() {
      var code = pre.querySelector('code');
      var text = code ? code.textContent : pre.textContent;
      var q = encodeURIComponent('Explain this code:\\n\\n' + text);
      window.open('https://claude.ai/new?q=' + q, '_blank');
    });

    wrapper.appendChild(copyBtn);
    wrapper.appendChild(aiBtn);
    pre.appendChild(wrapper);
  });
})();
</script>`;

// ── Table of Contents dropdown ────────────────────────────────────────
// Placeholder is stamped into each page, then replaced in a second pass
// once all titles are known from rendered HTML.

const TOC_PLACEHOLDER = '<!--TOC-->';

function buildTocHtml(currentSlug, titleMap) {
  let html = '';
  let lastGroup = '';
  for (const slug of NAV_ORDER) {
    const group = NAV_GROUP_MAP[slug];
    if (!titleMap[slug]) continue; // skip pages that weren't rendered
    if (group !== lastGroup) {
      html += `<div class="toc-group-label">${group}</div>\n`;
      lastGroup = group;
    }
    const label = titleMap[slug];
    const current = slug === currentSlug ? ' class="toc-current"' : '';
    html += `<a href="${slug}.html"${current}>${label}</a>\n`;
  }
  // Colophon at the end
  const colCurrent = currentSlug === 'colophon' ? ' class="toc-current"' : '';
  html += `<div class="toc-group-label">About</div>\n`;
  html += `<a href="colophon.html"${colCurrent}>Colophon</a>\n`;
  return html;
}

const CHEVRON_SVG = '<svg viewBox="0 0 10 6" fill="none"><path d="M1 1L5 5L9 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';

const TOC_SCRIPT = `<script>
(function() {
  var btn = document.getElementById('toc-btn');
  var panel = document.getElementById('toc-panel');
  if (!btn || !panel) return;
  btn.addEventListener('click', function(e) {
    e.stopPropagation();
    var open = panel.classList.toggle('open');
    btn.setAttribute('aria-expanded', open);
  });
  document.addEventListener('click', function(e) {
    if (!panel.contains(e.target) && e.target !== btn) {
      panel.classList.remove('open');
      btn.setAttribute('aria-expanded', 'false');
    }
  });
})();
</script>`;

// ── Generation footer ───────────────────────────────────────────────────
// Subtle footer showing generation timestamp and Claude Code version.

const DOCS_VERSION = (() => {
  try {
    const versionsDir = join(REPO_ROOT, "npm", "versions");
    const versions = readdirSync(versionsDir)
      .filter((f) => !f.startsWith("."))
      .sort((a, b) => {
        // Semver-aware sort: compare numeric parts
        const pa = a.replace(/^v/, "").split(".").map(Number);
        const pb = b.replace(/^v/, "").split(".").map(Number);
        for (let i = 0; i < 3; i++) {
          if ((pa[i] || 0) !== (pb[i] || 0)) return (pa[i] || 0) - (pb[i] || 0);
        }
        return 0;
      });
    if (versions.length > 0) return versions[versions.length - 1].replace(/^v/, "");
  } catch {}
  return "unknown";
})();

const GENERATED_AT = new Date().toLocaleString("en-US", {
  year: "numeric",
  month: "short",
  day: "numeric",
  hour: "numeric",
  minute: "2-digit",
  hour12: true,
});

const FOOTER_HTML = `<footer class="docset-footer">Generated ${GENERATED_AT} from Claude Code v${DOCS_VERSION}</footer>`;

// ── HTML template ──────────────────────────────────────────────────────

function htmlPage(title, body, hasTabs) {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <link rel="stylesheet" href="mintlify.css">
  <link rel="stylesheet" href="theme.css">
</head>
<body class="prose dark:prose-invert">
<div class="docset-logo">
  <div>
    <img class="logo-light" src="logo-light.svg" alt="Claude Code" height="28">
    <img class="logo-dark" src="logo-dark.svg" alt="Claude Code" height="28">
  </div>
  <div class="toc-wrapper">
    <button id="toc-btn" class="toc-button" aria-expanded="false" aria-controls="toc-panel">
      ${CHEVRON_SVG}<span>Table of Contents</span>
    </button>
    <div id="toc-panel" class="toc-panel" role="menu">
      ${TOC_PLACEHOLDER}
    </div>
  </div>
</div>
${body}
${FOOTER_HTML}
${hasTabs ? TAB_SCRIPT : ""}
${COPY_SCRIPT}
${TOC_SCRIPT}
</body>
</html>`;
}

// ── Suppress React DOM property warnings ────────────────────────────────
// Mintlify components use HTML attributes (srcset, fetchpriority) that
// React wants as camelCase (srcSet, fetchPriority). These warnings are
// harmless — renderToStaticMarkup still produces correct HTML.

const _origConsoleError = console.error;
console.error = (...args) => {
  if (typeof args[0] === "string" && args[0].includes("Invalid DOM property")) return;
  _origConsoleError.apply(console, args);
};

// ── Main ───────────────────────────────────────────────────────────────

if (!existsSync(buildDir)) mkdirSync(buildDir, { recursive: true });

// Copy CSS + logo assets
copyFileSync(
  join(dashDir, "node_modules", "@mintlify/components/dist/styles.css"),
  join(buildDir, "mintlify.css"),
);
copyFileSync(join(dashAssetsDir, "theme.css"), join(buildDir, "theme.css"));
copyFileSync(join(assetsDir, "logo-light.svg"), join(buildDir, "logo-light.svg"));
copyFileSync(join(assetsDir, "logo-dark.svg"), join(buildDir, "logo-dark.svg"));

const files = readdirSync(docsDir)
  .filter((f) => f.endsWith(".md"))
  .sort();
console.log(`Rendering ${files.length} docs...`);

let ok = 0;
let failed = 0;
let skipped = 0;
const errors = [];

for (const file of files) {
  const slug = basename(file, ".md");
  const mdPath = join(docsDir, file);
  const outPath = join(buildDir, `${slug}.html`);

  try {
    let md = readFileSync(mdPath, "utf-8");

    // Skip files that are full HTML pages (bad fetch, e.g. changelog)
    if (
      md.trimStart().startsWith("<!DOCTYPE") ||
      md.trimStart().startsWith("<html")
    ) {
      process.stdout.write(`  ~ ${slug} (not MDX, skipped)\n`);
      skipped++;
      continue;
    }

    // Preprocess: strip inline exports with hooks
    md = preprocessMdx(md);

    // Truncate changelog to avoid MDX serializer overflow
    if (slug === "changelog") {
      md = truncateChangelog(md);
    }

    const result = await serialize({ source: md });

    const element = createElement(MDXClient, {
      compiledSource: result.compiledSource,
      frontmatter: result.frontmatter,
      scope: result.scope,
      components: componentMap,
    });

    let body = renderToStaticMarkup(element);

    // Post-process: strip the llms.txt "Documentation Index" blockquote
    // that the fetch script prepends to every doc
    body = body.replace(
      /<blockquote>\s*<h2[^>]*>Documentation Index<\/h2>[\s\S]*?<\/blockquote>/,
      "",
    );

    body = rewriteLinks(body);
    body = injectSectionLabel(body, slug);
    body = convertPageDescription(body);
    body = injectDashAnchors(body);

    const title = extractTitle(body);
    const hasTabs = body.includes('role="tablist"');
    const html = htmlPage(title, body, hasTabs);

    writeFileSync(outPath, html);
    ok++;
    process.stdout.write(`  + ${slug}\n`);
  } catch (err) {
    failed++;
    errors.push({ slug, error: err.message });
    process.stderr.write(`  x ${slug}: ${err.message}\n`);
  }
}

// ── Render colophon page from shared assets ─────────────────────────────
const colophonPath = join(assetsDir, "colophon.md");
if (existsSync(colophonPath)) {
  try {
    const colophonMd = readFileSync(colophonPath, "utf-8");
    const colophonResult = await serialize({ source: colophonMd });
    const colophonEl = createElement(MDXClient, {
      compiledSource: colophonResult.compiledSource,
      frontmatter: colophonResult.frontmatter,
      scope: colophonResult.scope,
      components: componentMap,
    });
    const colophonBody = renderToStaticMarkup(colophonEl);
    const colophonHtml = htmlPage("Colophon", colophonBody, false);
    writeFileSync(join(buildDir, "colophon.html"), colophonHtml);
    process.stdout.write("  + colophon\n");
  } catch (err) {
    process.stderr.write(`  x colophon: ${err.message}\n`);
  }
}

// Write manifest for build-docset to consume.
// Uses NAV_ORDER so entries are inserted into the Dash SQLite index in
// site-navigation order (controls sidebar grouping/ordering in Dash).
const manifest = [];
for (const slug of NAV_ORDER) {
  const outPath = join(buildDir, `${slug}.html`);
  if (!existsSync(outPath)) continue;
  const html = readFileSync(outPath, "utf-8");
  const title = extractTitle(html);
  manifest.push({ slug, title, type: "Guide" });
}
// Also add any rendered pages not in NAV_ORDER (shouldn't happen, but safe)
for (const file of files) {
  const slug = basename(file, ".md");
  if (NAV_ORDER.includes(slug)) continue;
  const outPath = join(buildDir, `${slug}.html`);
  if (!existsSync(outPath)) continue;
  const html = readFileSync(outPath, "utf-8");
  const title = extractTitle(html);
  manifest.push({ slug, title, type: "Guide" });
}
// Add colophon as last entry
if (existsSync(join(buildDir, "colophon.html"))) {
  manifest.push({ slug: "colophon", title: "Colophon", type: "Guide" });
}
writeFileSync(join(buildDir, "index.json"), JSON.stringify(manifest, null, 2));
console.log(`Wrote index.json (${manifest.length} entries)`);

// ── Second pass: inject ToC with real titles ─────────────────────────
const titleMap = {};
for (const entry of manifest) {
  titleMap[entry.slug] = entry.title;
}

for (const entry of manifest) {
  const filePath = join(buildDir, `${entry.slug}.html`);
  let html = readFileSync(filePath, "utf-8");
  if (html.includes(TOC_PLACEHOLDER)) {
    const tocHtml = buildTocHtml(entry.slug, titleMap);
    html = html.replace(TOC_PLACEHOLDER, tocHtml);
    writeFileSync(filePath, html);
  }
}
console.log(`Injected ToC into ${manifest.length} pages`);

console.log(`\nDone: ${ok} rendered, ${skipped} skipped, ${failed} failed.`);
if (errors.length > 0) {
  console.log("\nFailed files:");
  for (const { slug, error } of errors) {
    console.log(`  ${slug}: ${error}`);
  }
}
